export const ticketsData = [
    {
        id: 1,
        titre: "Problème de connexion",
        description: "Je ne peux pas me connecter à mon compte",
        ticket: 'D0079',
        statut: "Ouvert",
        statutColor: "bg-green-500",
        dateCreation: "2025-03-15",
        priorite: "Haute",
        categorie: "Réseau",
        utilisateurId: "#U12345",
        technicien: "technicien 1",
    },
    {
        id: 2,
        titre: "Erreur système",
        description: "Mon ordinateur ne fonctionne pas correctement",
        ticket: 'D0076',
        statut: "Fermé",
        statutColor: "bg-red-500",
        dateCreation: "2025-03-14",
        priorite: "Moyenne",
        categorie: "Logiciel",
        utilisateurId: "#U67890",
        technicien: "technicien 2",
    },
    {
        id: 3,
        titre: "Demande de support",
        description: "Je voudrais savoir comment utiliser un logiciel",
        ticket: 'D0091',
        statut: "Ouvert",
        statutColor: "bg-green-500",
        dateCreation: "2025-03-13",
        priorite: "Basse",
        categorie: "Matériel",
        utilisateurId: "#U54321",
        technicien: "technicien 3",
    },
];